export const MUTATION_LOGIN = 'LOGIN_KEY'
export const MUTATION_REGISTER= 'REGISTER_KEY'
export const MUTATION_DELETE_APPLIS = 'DELETE_APPLIS'
export const MUTATION_CREATE_APPLIS = 'CREATE_APPLIS'

export const QUERY_GET_USERS = 'QUERY_GET_USERS_KEY'
export const QUERY_GET_APPLIS = 'QUERY_GET_APPLIS_KEY'